# This is a basic workflow to run npm commands on GitHub pages

name: NPM Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    # Runs the workflow only when files under the thoughts-principles-react directory are changed
    paths:
      - 'thoughts-principles-react/**'
  pull_request:
    branches: [ main ]
    # Runs the workflow only when files under the thoughts-principles-react directory are changed
    paths:
      - 'thoughts-principles-react/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the npm commands inside the thoughts-principles-react directory
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Changes the working directory to the thoughts-principles-react directory
      - name: Change directory
        run: cd thoughts-principles-react

      # Runs npm install and npm run build commands
      - name: Run npm commands
        run: |
          pwd
          npm i
          npm run build

      # Commits the changes with the specified message
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automated:Thoughts and principles build."
          git push
