# This is a basic workflow to run npm commands on GitHub pages

name: NPM Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    # Runs the workflow only when files under below specified directory are changed
    paths:
      - 'thoughts/thoughts-frontend/**'
  pull_request:
    branches: [ main ]
    # Runs the workflow only when files under below specified directory are changed
    paths:
      - 'thoughts/thoughts-frontend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the npm commands
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set defaults for all steps in a job
    defaults:
      run:
        # Changes the working directory below specifed path (Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun)
        working-directory: ./thoughts/thoughts-frontend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs npm install and npm run build commands
      - name: Run npm commands
        run: |
          # Using pwd here to debug the path of the directoy in which the commands will run
          pwd
          npm ci
          npm run build

      # Commits the changes with the specified message
      - name: Commit changes
        run: |
          # Go to parent directory of default `working-directory`
          cd ..
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automated:Thoughts and principles build."
          git push
